package io.github.lukedevops.yukon.instrumentation

import io.github.lukedevops.yukon.config.AgentConfig
import io.github.lukedevops.yukon.export.ResourceAttributes
import io.github.lukedevops.yukon.registry.ProbeRegistry
import javassist.util.proxy.ProxyFactory
import net.bytebuddy.ByteBuddy
import net.bytebuddy.NamingStrategy
import net.bytebuddy.agent.ByteBuddyAgent
import net.bytebuddy.agent.builder.ResettableClassFileTransformer
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy
import java.io.File
import java.lang.instrument.ClassFileTransformer
import java.lang.instrument.Instrumentation
import java.lang.reflect.InvocationHandler
import java.lang.reflect.Proxy
import java.security.ProtectionDomain
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Drives ByteBuddy, javassist and the JDK's proxy generator under the installed agent, in the
 * fixture package, and checks each class they define reaches the transformer chain and is left
 * alone: no probes, no skipped entry, and no report from the sweep. Mockito is not a dependency, so
 * its name is made with ByteBuddy's `SuffixingRandom("MockitoMock")`, the same `%s$%s$%s` shape and
 * `RandomString.make()` tail as Mockito's `SubclassBytecodeGenerator`. A class ByteBuddy defines
 * under a name of the adopter's own kind is registered as usual, which shows the transformer weaves
 * generated bytes when nothing turns them away.
 */
class RuntimeGeneratedClassTest {
    private companion object {
        const val PACKAGE = "com.example.target"
        const val BASE = "$PACKAGE.SampleTarget"
        const val PACKAGE_PRIVATE_INTERFACE = "$PACKAGE.PackagePrivateGreeter"
        const val NAMING_PROPERTY = "net.bytebuddy.naming"
    }

    private val instrumentation: Instrumentation = ByteBuddyAgent.install()
    private var yukon: YukonInstrumentation? = null
    private var installedTransformer: ResettableClassFileTransformer? = null
    private var watcher: ClassFileTransformer? = null

    @AfterTest
    fun tearDown() {
        installedTransformer?.let { yukon?.uninstall(instrumentation, it) }
        watcher?.let { instrumentation.removeTransformer(it) }
    }

    @Test
    fun `classes ByteBuddy, Mockito, javassist and the JDK generate are offered to the agent and left alone`() {
        val offered = mutableSetOf<String>()
        val spy =
            object : ClassFileTransformer {
                override fun transform(
                    loader: ClassLoader?,
                    className: String?,
                    classBeingRedefined: Class<*>?,
                    protectionDomain: ProtectionDomain?,
                    classfileBuffer: ByteArray,
                ): ByteArray? {
                    if (className != null && className.startsWith("com/example/target/")) {
                        synchronized(offered) { offered += className.replace('/', '.') }
                    }
                    return null
                }
            }
        instrumentation.addTransformer(spy, false)
        watcher = spy

        val registry = ProbeRegistry()
        val config = AgentConfig.parse("includePackages=$PACKAGE")
        val instrumented = YukonInstrumentation(config, registry)
        yukon = instrumented
        installedTransformer = instrumented.install(instrumentation)

        val loader = FixtureClassLoader(arrayOf(File("build/classes/java/test").toURI().toURL()), javaClass.classLoader)
        val base = Class.forName(BASE, true, loader)

        val byteBuddy =
            ByteBuddy()
                .subclass(base)
                .make()
                .load(loader, ClassLoadingStrategy.Default.WRAPPER)
                .loaded
        val mockitoShaped =
            ByteBuddy()
                .with(NamingStrategy.SuffixingRandom("MockitoMock"))
                .subclass(base)
                .make()
                .load(loader, ClassLoadingStrategy.Default.WRAPPER)
                .loaded
        val javassist = ProxyFactory().apply { superclass = base }.createClass()
        val greeter = Class.forName(PACKAGE_PRIVATE_INTERFACE, true, loader)
        val jdkProxy = Proxy.newProxyInstance(loader, arrayOf(greeter), InvocationHandler { _, _, _ -> "hi" }).javaClass
        val named =
            ByteBuddy()
                .subclass(base)
                .name("$PACKAGE.SampleTargetSubclass")
                .make()
                .load(loader, ClassLoadingStrategy.Default.WRAPPER)
                .loaded

        val generated = listOf(byteBuddy, mockitoShaped, javassist, jdkProxy).map { it.name }
        assertTrue("\$ByteBuddy\$" in byteBuddy.name, byteBuddy.name)
        assertTrue("\$MockitoMock\$" in mockitoShaped.name, mockitoShaped.name)
        assertTrue("_\$\$_jvst" in javassist.name, javassist.name)
        assertTrue(jdkProxy.name.startsWith("$PACKAGE.\$Proxy"), jdkProxy.name)
        for (name in generated + named.name) {
            assertTrue(name in synchronized(offered) { offered.toSet() }, "$name never reached a transformer, so this proved nothing")
        }

        LoadedClassSweep(instrumentation, registry, config).run(runForwardPass = true)
        val manifest = registry.manifest(ResourceAttributes("test", null, "instance-1", null, "run-1"))
        for (name in generated) {
            assertTrue(manifest.probes.none { it.className == name }, "$name was woven")
            assertTrue(manifest.skippedClasses.none { it.className == name }, "$name was reported skipped")
            assertTrue(manifest.unreportedClasses.none { it.className == name }, "$name was reported by the sweep")
        }
        assertTrue(manifest.probes.any { it.className == named.name }, "a ByteBuddy class under an ordinary name is woven")
    }

    /**
     * Under `-Dnet.bytebuddy.naming=fixed` a default `ByteBuddy` instance names its types with
     * `NamingStrategy.Suffixing("ByteBuddy", ForUnnamedType, "net.bytebuddy.renamed")`, which gives
     * `<base>$ByteBuddy` with no tail. The strategy is used directly here, since this JVM's own
     * `ByteBuddy` class read the property long before the test ran. The class is left alone while
     * the property selects that mode, and woven as the adopter's own when it does not.
     */
    @Test
    fun `a class ByteBuddy names under the fixed naming mode is left alone only while that mode is on`() {
        val registry = ProbeRegistry()
        val config = AgentConfig.parse("includePackages=$PACKAGE")
        val instrumented = YukonInstrumentation(config, registry)
        yukon = instrumented
        installedTransformer = instrumented.install(instrumentation)

        fun defineFixedNamed(): Class<*> {
            val loader = FixtureClassLoader(arrayOf(File("build/classes/java/test").toURI().toURL()), javaClass.classLoader)
            val base = Class.forName(BASE, true, loader)
            return ByteBuddy()
                .with(
                    NamingStrategy.Suffixing(
                        "ByteBuddy",
                        NamingStrategy.Suffixing.BaseNameResolver.ForUnnamedType.INSTANCE,
                        "net.bytebuddy.renamed",
                    ),
                ).subclass(base)
                .make()
                .load(loader, ClassLoadingStrategy.Default.WRAPPER)
                .loaded
        }

        val woven = defineFixedNamed()
        val previous = System.setProperty(NAMING_PROPERTY, "fixed")
        val leftAlone =
            try {
                defineFixedNamed()
            } finally {
                if (previous == null) System.clearProperty(NAMING_PROPERTY) else System.setProperty(NAMING_PROPERTY, previous)
            }

        assertTrue(woven.name == "$BASE\$ByteBuddy" && leftAlone.name == woven.name, "${woven.name} ${leftAlone.name}")
        val probes =
            registry.manifest(ResourceAttributes("test", null, "instance-1", null, "run-1")).probes.filter {
                it.className ==
                    woven.name
            }
        assertEquals(1, probes.map { it.classId }.distinct().size, "exactly one of the two copies is woven: $probes")
    }
}
